// Consult I sensor register map. Addresses and scalings are the common ones
// (SR20, RB, KA, CA ECUs); some ECUs only support a subset — unsupported
// registers just read back garbage or 0xFF, so deselect any that look wrong.
//
// `regs` lists the register addresses (MSB first for 16-bit values) and
// `convert` turns the raw byte(s) into a display value.

const SENSORS = [
  {
    id: 'rpm',
    name: 'Engine RPM',
    unit: 'rpm',
    regs: [0x00, 0x01],
    convert: (msb, lsb) => ((msb << 8) | lsb) * 12.5,
    decimals: 0,
  },
  {
    id: 'maf',
    name: 'MAF voltage (LH)',
    unit: 'mV',
    regs: [0x04, 0x05],
    convert: (msb, lsb) => ((msb << 8) | lsb) * 5,
    decimals: 0,
  },
  {
    id: 'maf_rh',
    name: 'MAF voltage (RH)',
    unit: 'mV',
    regs: [0x06, 0x07],
    convert: (msb, lsb) => ((msb << 8) | lsb) * 5,
    decimals: 0,
  },
  {
    id: 'coolant',
    name: 'Coolant temp',
    unit: '°C',
    regs: [0x08],
    convert: (b) => b - 50,
    decimals: 0,
  },
  {
    id: 'o2',
    name: 'O2 sensor (LH)',
    unit: 'mV',
    regs: [0x09],
    convert: (b) => b * 10,
    decimals: 0,
  },
  {
    id: 'o2_rh',
    name: 'O2 sensor (RH)',
    unit: 'mV',
    regs: [0x0a],
    convert: (b) => b * 10,
    decimals: 0,
  },
  {
    id: 'speed',
    name: 'Vehicle speed',
    unit: 'km/h',
    regs: [0x0b],
    convert: (b) => b * 2,
    decimals: 0,
  },
  {
    id: 'battery',
    name: 'Battery voltage',
    unit: 'V',
    regs: [0x0c],
    convert: (b) => (b * 80) / 1000,
    decimals: 1,
  },
  {
    id: 'tps',
    name: 'Throttle position',
    unit: 'mV',
    regs: [0x0d],
    convert: (b) => b * 20,
    decimals: 0,
  },
  {
    id: 'iat',
    name: 'Intake air temp',
    unit: '°C',
    regs: [0x11],
    convert: (b) => b - 50,
    decimals: 0,
  },
  {
    id: 'injector',
    name: 'Injector pulse (LH)',
    unit: 'ms',
    regs: [0x14, 0x15],
    convert: (msb, lsb) => ((msb << 8) | lsb) / 100,
    decimals: 2,
  },
  {
    id: 'timing',
    name: 'Ignition timing',
    unit: '° BTDC',
    regs: [0x16],
    convert: (b) => 110 - b,
    decimals: 0,
  },
  {
    id: 'aac',
    name: 'AAC valve (idle)',
    unit: '%',
    regs: [0x17],
    convert: (b) => b / 2,
    decimals: 1,
  },
  {
    id: 'injector_rh',
    name: 'Injector pulse (RH)',
    unit: 'ms',
    regs: [0x22, 0x23],
    convert: (msb, lsb) => ((msb << 8) | lsb) / 100,
    decimals: 2,
  },
  {
    id: 'alpha',
    name: 'A/F alpha (LH)',
    unit: '%',
    regs: [0x1a],
    convert: (b) => b,
    decimals: 0,
  },
  {
    id: 'alpha_rh',
    name: 'A/F alpha (RH)',
    unit: '%',
    regs: [0x1b],
    convert: (b) => b,
    decimals: 0,
  },
];

// Names for the register scanner, from the "Generic Nissan ECU Sensor or
// Data register table Ver 2" (Nissan Technical egroup). Any given ECU only
// answers a subset of these.
const REGISTER_NAMES = {
  0x00: 'CAS position RPM (MSB)',
  0x01: 'CAS position RPM (LSB)',
  0x02: 'CAS reference RPM (MSB)',
  0x03: 'CAS reference RPM (LSB)',
  0x04: 'MAF voltage LH (MSB)',
  0x05: 'MAF voltage LH (LSB)',
  0x06: 'MAF voltage RH (MSB)',
  0x07: 'MAF voltage RH (LSB)',
  0x08: 'Coolant temp',
  0x09: 'O2 sensor LH',
  0x0a: 'O2 sensor RH',
  0x0b: 'Vehicle speed',
  0x0c: 'Battery voltage',
  0x0d: 'Throttle position',
  0x0f: 'Fuel temp',
  0x11: 'Intake air temp',
  0x12: 'Exhaust gas temp',
  0x13: 'Digital inputs (A/C, P/S, neutral, start, closed TPS)',
  0x14: 'Injection time LH (MSB)',
  0x15: 'Injection time LH (LSB)',
  0x16: 'Ignition timing',
  0x17: 'AAC valve',
  0x1a: 'A/F alpha LH',
  0x1b: 'A/F alpha RH',
  0x1c: 'A/F alpha LH (self-learn)',
  0x1d: 'A/F alpha RH (self-learn)',
  0x1e: 'Digital control (A/C relay, fuel pump, VTC, fans)',
  0x1f: 'Digital control (P/reg, wastegate sol, FICD, EGR)',
  0x21: 'Mixture monitor (LH/RH lean flags)',
  0x22: 'Injection time RH (MSB)',
  0x23: 'Injection time RH (LSB)',
  0x25: 'Purge volume control valve step',
  0x26: 'Tank fuel temp',
  0x27: 'FPCM DR voltage',
  0x28: 'Wastegate solenoid %',
  0x29: 'Turbo boost sensor voltage',
  0x2a: 'Engine mount on/off',
  0x2e: 'Position counter',
  0x2f: 'Fuel gauge voltage',
  0x30: 'Front O2 heater B1',
  0x31: 'Front O2 heater B2',
  0x32: 'Ignition switch',
  0x33: 'CAL/LD value %',
  0x34: 'Base fuel schedule',
  0x35: 'Rear O2 sensor',
  0x36: 'Rear O2 sensor B2',
  0x37: 'Absolute throttle position',
  0x38: 'MAF g/s',
  0x39: 'Evap system pressure',
  0x3a: 'Absolute pressure sensor (MSB)',
  0x4a: 'Absolute pressure sensor (LSB)',
  0x52: 'FPCM fuel pressure (MSB)',
  0x53: 'FPCM fuel pressure (LSB)',
};

// Fault code descriptions (common across most Consult I ECUs).
const FAULT_CODES = {
  11: 'Crank angle sensor / circuit',
  12: 'Mass air flow sensor',
  13: 'Engine coolant temperature sensor',
  14: 'Vehicle speed sensor',
  21: 'Ignition signal',
  22: 'Fuel pump circuit',
  23: 'Idle switch',
  24: 'Throttle valve switch',
  25: 'Idle speed control (AAC) valve',
  28: 'Cooling fan circuit',
  31: 'ECM (control unit)',
  32: 'EGR function',
  33: 'Oxygen sensor',
  34: 'Knock sensor',
  35: 'Exhaust gas temperature sensor',
  43: 'Throttle position sensor',
  45: 'Injector leak',
  51: 'Injector circuit',
  54: 'A/T control signal',
  55: 'No malfunction',
};

// Bit-packed status registers (one byte = eight on/off flags). Bit positions
// are from the generic Nissan register table; ordering varies between ECUs,
// so the panel shows the raw byte and the intent is to confirm a bit by
// toggling its switch and watching it flip. Bit assignments here match the
// values observed on a real RB26 (0x13=0x05 at idle, 0x21=0xC0 cold/lean).
const FLAG_REGISTERS = [
  {
    reg: 0x13,
    name: 'Input switches',
    bits: {
      0: 'Closed throttle (idle)',
      1: 'Start signal (cranking)',
      2: 'Park / Neutral',
      3: 'Power steering',
      4: 'A/C switch',
    },
  },
  {
    reg: 0x1e,
    name: 'Relays & actuators',
    bits: {
      7: 'A/C relay',
      6: 'Fuel pump relay',
      5: 'VTC solenoid',
      4: 'Coolant fan (Hi)',
      3: 'Coolant fan (Lo)',
    },
  },
  {
    reg: 0x1f,
    name: 'Solenoids',
    bits: {
      7: 'P/reg control valve',
      6: 'Wastegate solenoid',
      5: 'IACV-FICD solenoid',
      4: 'EGR solenoid',
    },
  },
  {
    reg: 0x21,
    name: 'Mixture (closed-loop)',
    bits: {
      7: 'LH bank lean',
      6: 'RH bank lean',
    },
  },
];

module.exports = { SENSORS, FAULT_CODES, REGISTER_NAMES, FLAG_REGISTERS };
